name: Zig Build and Lint

on:
  push:
    branches: [ "main", "github-actions-2" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
          zig_version: ['0.13.0']
          #os: [ubuntu-latest, windows-latest, macOS-latest]
          os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: mlugg/setup-zig@v1
        with:
          version: ${{ matrix.zig_version }}
      - name: Install OpenGL and glfw (Linux)
        if: runner.os == 'Linux'
        run: |
          apt-get install libglew-dev
          apt-get install libglfw3
      - run: zig build

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: mlugg/setup-zig@v1
        with:
          version: '0.13.0'
      - run: zig fmt --check .